sudo: required
services:
  - docker


before_install:
  - docker build -t angelos1989/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run angelos1989/react-test npm test -- --coverage


after_success:
  - docker build -t angelos1989/multi-client ./client
  - docker build -t angelos1989/multi-nginx ./nginx
  - docker build -t angelos1989/multi-server ./server
  - docker build -t angelos1989/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push to docker hub
  - docker push angelos1989/multi-client
  - docker push angelos1989/multi-nginx
  - docker push angelos1989/multi-server
  - docker push angelos1989/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-249851427308
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
